- name: Run tests and generate report
  if: steps.changed.outputs.py_files == 'true'
  shell: bash -l {0}
  run: |
    set +e  # 禁用自动失败
    # 捕获测试输出（允许失败）
    output=$(maintenance/tests/DO_TEST.sh 2>&1)
    exit_code=$?
    set -e  # 恢复错误检查

    # 生成报告文件
    isoDateTime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    commit="${GITHUB_SHA::7}"
    
    # 动态生成报告内容
    {
      echo "## Test Report - $isoDateTime"
      echo "**Commit:** $commit"
      [ $exit_code -eq 0 ] && echo "**Status:** ✅ All tests passed" || echo "**Status:** ❌ Some tests failed"
      echo "\n### Execution Log:\n\`\`\`"
      echo "$output"
      echo "\`\`\`"
    } > TEST.md

    # Git操作配置
    git config --global user.name "Twinkle"
    git config --global user.email "twinkle@lesboys.org"

    # 提交操作（带异常处理）
    git add TEST.md
    git commit -m "+ACTION: Auto-test report update" || true  # 允许空提交失败
    
    # 关键清理操作
    git clean -fdx  # 强制清理未跟踪文件
    
    # 强制推送（确保触发后续流程）
    git push origin HEAD:${GITHUB_REF#refs/heads/} -f